# Generated by Django 3.0.2 on 2020-02-07 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('per_class_duration', models.IntegerField()),
                ('totalDuration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField()),
                ('salary_per_annum', models.FloatField()),
                ('web_lecture_capability', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.School')),
                ('subjects', models.ManyToManyField(to='School.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.User')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField()),
                ('standard', models.IntegerField()),
                ('roll_num', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('cls', models.ManyToManyField(related_name='students', to='School.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.User')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.School')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.ClassRoom'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='School.Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.Teacher'),
        ),
    ]
