# Generated by Django 3.0.2 on 2020-01-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_class_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmapping',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='School.Class'),
        ),
    ]
