# Generated by Django 3.0.2 on 2020-02-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_auto_20200131_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmapping',
            name='subject',
        ),
        migrations.AlterField(
            model_name='subjectmapping',
            name='class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='School.Class'),
        ),
    ]
